version: "3"

services:

  nlp-processing:

    build: .
    container_name: nlp-processing
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app

  logstash-service:

    build: ./logstash/

    command: logstash -f /logstash.conf

    ports:
    - "9200:9200"

    container_name: logstash-service-nlp

    env_file:
      - ./app/.env
    volumes:
      - ./app/app.log:/app.log:ro
      - ./logstash/logstash.conf:/logstash.conf