name: CD
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        password: ${{ secrets.PASSWORD }}
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOST }}
        script: |
          cd nlp-processing
          git pull origin master
          bash deploy.sh